Add missing required modules
Fix error:
=====================
In file included from /home/kchsieh/Workspace/fibocom/fibocom_linux_apps_opensource/application/fibo_helper_service/fibo_helper_main.c:24:
/home/kchsieh/Workspace/fibocom/fibocom_linux_apps_opensource/application/fibo_helper_service/fibo_helper_basic_func.h:27:10: fatal error: libmbim-glib.h: No such file
 or directory
   27 | #include "libmbim-glib.h"
      |          ^~~~~~~~~~~~~~~~
compilation terminated.
====================
and
====================
/home/kchsieh/Workspace/fibocom/fibocom_linux_apps_opensource/application/fibo_helper_service/fibo_helper_basic_func.c:25:10: fatal error: libmm-glib.h: No such file or directory
   25 | #include <libmm-glib.h>
      |          ^~~~~~~~~~~~~~
compilation terminated.
===================